# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting Started'
  link: '/getting-started'
- label: Reference
  items:
    - label: 'Convert'
      link: '/usage/convert'
    - label: 'Create Destinations'
      link: '/usage/create_destinations'
    - label: 'Format Blank Lines'
      link: '/usage/format_blank_lines'
    - label: 'Format Leading Whitespace'
      link: '/usage/format_leading_whitespace'
    - label: 'Format Md Table'
      link: '/usage/format_md_table'
    - label: 'Format Path'
      link: '/usage/format_path'
    - label: 'Format Rd Path'
      link: '/usage/format_rd_path'
    - label: 'Format Yaml Keywords'
      link: '/usage/format_yaml_keywords'
    - label: 'Format Yaml Text'
      link: '/usage/format_yaml_text'
- label: Community
  items:
    - label: 'rdConvert'
      link: 'https://github.com/davidruvolo51/rdConvert'
